### ISSUE TITLE
Compatibility with react-native

### ISSUE THREAD

**Issue by tastycode** [cpunion/react-actioncable-provider#5]
![image](https://user-images.githubusercontent.com/809953/28702870-cf7279a6-7314-11e7-842b-50ffb383c97f.png)

**Comment by tastycode** [comment]
This is covered in the readme for `react-native-actioncable` a link might be helpful from the Readme. https://github.com/cpunion/react-native-actioncable#use-with-react-actioncable-provider. Let me know and I can add.

**Comment by cpunion** [comment]
@tastycode That's good. Feel free to open PRs. :-)
