### ISSUE TITLE
Deployment fails because of dependency

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [cpunion/react-actioncable-provider#9]
When I try deploying an app bootstrapped with create-react-app and your dependency, deployment fails with the following error:

```remote: Module not found: Error: Can't resolve 'create-react-class' in '/tmp/build_97a69fac11256a030f21ad2eeb0d2cef/node_modules/react-actioncable-provider'```

**Comment by cpunion** [comment]
Thanks. Added missing dependency `react-create-class` in https://github.com/cpunion/react-actioncable-provider/commit/58658506b7026f796e2f7c5495ea94504289b6a5, and released version `1.0.1`.
